[build]
  base = "client"
  publish = "build"
  command = "npm run build"

# Remove or comment out functions setting unless you use Netlify Functions:
# functions = "my_functions"

[[redirects]]
  from = "/api/*"
  to = "https://fin-tracker-2-odkq.onrender.com/api/:splat"
  status = 200
